# Setup
title: Boettiger Lab at Stanford University
description: Welcome!  We are an interdiscplinary group of scientists in the department of Developmental biology, seeking to better understand the mechanisms that regulate gene expression in development and disease. 
github_username: BoettigerLab

cover_image: https://boettigerlab.github.io/images/lasers2.jpg

# Author
author:
  name:       Alistair Boettiger
